name: njsscan
on:
  merge_group:
    branches:
      - main
      - dev
      - staging
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging
    types: 
      - ready_for_review
      - review_requested

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: scan
        run: make scan 