#!/bin/sh

forbidden_commit="tmp"

while read local_ref local_sha remote_ref remote_sha
do
    # Collect all commit messages for commits being pushed
    commit_messages=$(git log --format=%B $remote_sha..$local_sha)

    # Check each commit message
    echo "$commit_messages" | while read -r line; do
        if [[ "$line" == "$forbidden_commit"* ]]; then
            echo "Error: Commit messages of type '$forbidden_commit' are not allowed to be pushed"
            exit 1
        fi
    done

    # Capture the exit status of the last command in the pipeline
    status=$?

    # If an error was found, exit with status 1
    if [ $status -ne 0 ]; then
        exit 1
    fi
done

exit 0