name: Run linting and tests

on:
  push:
    branches-ignore:
      - HCLOUD-1996_Use-semantic-release-to-generate-changelog-from-commit-messages-in-js-SDK-and-to-release_Darius-Weiberg-3 # When pushing/merging to branch 'staging' (or later main), buildAndPublish workflow will already do the testing
      - main

jobs:
  run:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare packages
        run: make prepare

      - name: Lint
        run: make lint

      - name: Test (Unit)
        run: make test
