name: Run linting and tests

on:
  push:
    branches-ignore:
      - staging # When pushing/merging to branch 'staging' (or later main), buildAndPublish workflow will already do the testing

jobs:
  run:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.14.0]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare packages
        run: make prepare

      - name: Lint
        run: make lint

      - name: Test (Unit)
        run: make test
